# Generated by Django 6.0 on 2026-02-15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image_refs',
            field=models.JSONField(
                blank=True,
                default=list,
                help_text='Storage keys/paths for images, same order as image_urls',
            ),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='image_refs',
            field=models.JSONField(
                blank=True,
                default=list,
                help_text='Storage keys/paths for images, same order as image_urls',
            ),
        ),
    ]
