# Generated by Django 6.0

from decimal import Decimal

from django.db import migrations, models


def backfill_product_rating(apps, schema_editor):
    Product = apps.get_model("products", "Product")
    ProductReview = apps.get_model("products", "ProductReview")
    for product in Product.objects.all():
        reviews = ProductReview.objects.filter(product=product)
        count = reviews.count()
        if count:
            avg = sum(r.rating for r in reviews) / count
            product.avg_rating = round(Decimal(str(avg)), 2)
            product.review_count = count
        else:
            product.avg_rating = None
            product.review_count = 0
        product.save(update_fields=["avg_rating", "review_count"])


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0005_add_product_reviews_and_comments"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="avg_rating",
            field=models.DecimalField(
                blank=True,
                db_index=True,
                decimal_places=2,
                max_digits=3,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="review_count",
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
        migrations.RunPython(backfill_product_rating, migrations.RunPython.noop),
        migrations.DeleteModel(
            name="ProductComment",
        ),
    ]
