# Generated by Django 6.0 on 2026-03-02 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_remove_comments_add_avg_rating'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='productreview',
            new_name='products_pr_product_c9febd_idx',
            old_name='products_pr_product_8a1b2c_idx',
        ),
    ]
