# Generated by Django 6.0

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0001_initial"),
        ("products", "0007_rename_products_pr_product_8a1b2c_idx_products_pr_product_c9febd_idx"),
    ]

    operations = [
        migrations.AddField(
            model_name="productreview",
            name="order",
            field=models.ForeignKey(
                blank=True,
                help_text="Completed order that contained this product (verified on create).",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="product_reviews",
                to="orders.order",
            ),
        ),
        migrations.AddField(
            model_name="productreview",
            name="is_anonymous",
            field=models.BooleanField(
                default=False,
                help_text="If true, user_display is redacted as 'Anonymous'.",
            ),
        ),
    ]
