# Generated by Django 6.0 on 2025-12-13 02:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, db_index=True, help_text='Email address to verify', max_length=254, null=True)),
                ('phone', models.CharField(blank=True, db_index=True, help_text='Phone number to verify', max_length=17, null=True)),
                ('is_used', models.BooleanField(default=False, help_text='OTP has been used')),
                ('attempt_count', models.IntegerField(default=0, help_text='Number of failed attempts to verify OTP')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(help_text='OTP expiration time (5 minutes from creation)')),
                ('otp', models.CharField(max_length=6)),
            ],
        ),
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(blank=True, db_index=True, max_length=254, null=True, unique=True, validators=[django.core.validators.EmailValidator()], verbose_name='email address'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='phone',
            field=models.CharField(blank=True, db_index=True, max_length=17, null=True, unique=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+129999999'. Up to 17 digits allowed.", regex='^\\+?1?\\d{9,17}$')], verbose_name='phone number'),
        ),
    ]
