# Generated by Django 6.0 on 2026-01-19 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_otp_alter_customuser_email_alter_customuser_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='image_url',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='profile image url'),
        ),
    ]
