# Generated by Django 6.0 on 2026-02-15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_customuser_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='image_ref',
            field=models.CharField(
                blank=True,
                help_text='Storage key or path for the profile image',
                max_length=500,
                null=True,
                verbose_name='profile image ref',
            ),
        ),
    ]
