# Generated by Django 6.0 on 2026-02-12 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0003_category_author_image_alt_author_image_ref_and_more'),
        ('products', '0003_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='related_products',
            field=models.ManyToManyField(blank=True, related_name='blog_posts', to='products.product'),
        ),
    ]
