# Generated by Django 6.0 on 2026-02-15 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0004_post_related_products'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='featured_image_url',
            field=models.URLField(blank=True, max_length=500),
        ),
    ]
